hydra:
  run:
    dir: out/logs/${now:%Y-%m-%d} # /${now:%H-%M-%S}
  sweep:
    dir: out/logs/${now:%Y-%m-%d}/multirun # /${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: False
  job_logging:
    version: 1
    handlers:
      console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
    formatters:
      simple:
        format: '%(message)s'

defaults:
  - _self_
  - model: proposal

io:
  input_dir: ???
  uuid: 1
  root_out_dir: out/
  tag: null
  # preprocessing of input data
  logarithm: False
  zscore: True
  minmax_scale: False
  normalize: False
  whitenoise: 0
  moving_average: 1

seed: 42
use_gpu: False
use_multi_gpu: False
devices: "0,1,2,3"
save: True
verbose: True
